### ISSUE TITLE
[ip_support_search_form] Form Return No Result

### ISSUE THREAD

**Issue by ataylorme** [LiftUX/IssuePress#168] opened 2014-10-09 20:55 UTC
Have the `[ip_support_search_form]` shortcode isolated on a page.

One open issue with the name "Test Issue"

Searching for "Test Issue" (or anything else) yields nothing upon page reload.

No console errors or anything to note.

Using fresh WordPress install with TwentyFourteen and IssuePress being the only plugin to eliminate conflicts.

Permalinks set to `Post name` and flushed.

IssuePress general options filled out as well.

Screenshots attached.

![screen shot 2014-10-09 at 3 52 22 pm](https://cloud.githubusercontent.com/assets/2133004/4583954/99297a82-4ff6-11e4-8104-529626ff7284.png)
![screen shot 2014-10-09 at 3 55 14 pm](https://cloud.githubusercontent.com/assets/2133004/4583955/99335c50-4ff6-11e4-8458-1ce4a19c3919.png)

**Comment by matthewsimo** [comment] 2014-10-09 21:59
This is a dupe of #160  - closing but will update there.

**Closed as completed by matthewsimo** 2014-10-09 21:59 UTC
Labels: bug, duplicate, issuepress
