### ISSUE TITLE
Front End App Built Out

### ISSUE THREAD

**Issue by imbradmiller** [LiftUX/IssuePress#22] opened 2013-06-27 21:17 UTC
- [x] Move to Angular
- [x] Integrate static prototype code into front end app
- [x] Build handling for Widget System on front-end
- [x] Verify AJAX Endpoints are returning data correctly

**Comment by matthewsimo** [comment] 2013-06-27 22:02
This is a dupe of #4 - so I close that one in favor of this which is more detailed.

**Comment by matthewsimo** [comment] 2013-06-27 22:10
Guys - I'm considering using Angular instead of Backbone for this. We have a bit of rough outline stuff for backbone currently but not too much actual functional code since the static prototype wasn't even made when I first laid it down. 

Angular give us some great features out of the box that we'll take advantage of but would have to implement if we used BB. Want at least one :+1: before I actually decide to take the useful stuff already in there and throw away backbone...

**Comment by imbradmiller** [comment] 2013-06-27 22:12
Based on my technical knowledge of each I'd say I trust your decision on this. @chriswallace do you have any objections to this?

**Comment by chriswallace** [comment] 2013-06-28 15:10
Personally, I'd like to keep Backbone because it's already in WordPress Core. It would be a good case study for WordPress developers on building JS-based plugins for WP using libraries already included in WP Core. Please explain some of the benefits of using Angular so we can make an informed decision which way to go.

**Comment by matthewsimo** [comment] 2013-06-28 15:25
The major reason lies in angular's built in two-way data & filtering directives. Without going into it too much of either feature (more info can be found on the angular site about these topics),  they basically automatically handle complicated code pieces that are typically error prone & hard to test/debug.

Brief overview of each:

#### Two way data binding
- The data in the angular model automatically updates itself when it changes somewhere. So there isn't a bunch of the spaghetti code that needs to get written to make sure a piece of data stays in sync throughout the template/page. (This also takes into account if you are fetching data from an end-point like we are - when the data the back end sends back updates angular will update anywhere that data is bound.)

#### Filtering Directives
- Angular has built in filtering, so we can really quickly add the feature we wanted where we use the search box to filter/show proper results. Building this out in a BB app will be very complicated and take a long time to get "right" - we'd effectively have to build a parser to return results properly (very difficult to do well).

There are other benefits but these are the BIG ones that I think really reinforce the benefits.

**Comment by chriswallace** [comment] 2013-06-28 15:28
OK, thanks for the explanation. Proceed.

**Comment by matthewsimo** [comment] 2013-06-28 15:29
If you want an example of the filtering directive, there is a good one on the angular homepage under the "Wire Up a Backend" section - http://angularjs.org/

**Comment by matthewsimo** [comment] 2013-06-28 15:32
Thanks, proceeding!

**Comment by matthewsimo** [comment] 2013-09-16 22:56
Going to go ahead and close this out since we have the front-end built out and we are finishing/refining features for beta now. Thanks, feel free to re-open if you have a good reason.

**Closed as completed by matthewsimo** 2013-09-16 22:56 UTC
